### ISSUE TITLE
Fucked up

### ISSUE THREAD

**Issue by damixk** [kubp/daku#2]
Styly který napovídají k čemu patří.... 
#acc{
	display:block !important; <---- co to tam dělá? 
}
#accs
#footer-c

Responzivita lvl :100: @Hribek  <a href="http://cloud.damixk.eu/graficiLogic.mp4"> někam to odjíždí </a>

**Comment by kubp** [comment]
A ještě tam máš tohle #1. Pořád to není roztáhlý. A chtělo by to tam dát třeba cenu atd ..
